name: cicd-static-app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.1

    - name: Setup Node.js
      uses: actions/setup-node@v4.0.4
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Run linters
      id: selint
      run: |
        set -e
        output=$(npx eslint 'script.js' --max-warnings 0 2>&1)
        echo "linter_output=$output" >> $GITHUB_ENV
        
    - name: Send fail message to Telegram 
      if: ${{ failure() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Failed ${{ github.job }}
          ${{ github.actor }} created commit:
          Commit message: ${{ github.event.commits[0].message }}
          
          Repository: ${{ github.repository }}
          
          Linter output:
          ```
          ${{ env.linter_output }}
          ```

    - name: Deploy to GitHub Pages
      if: ${{ success() }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        branch: gh-pages
        single-commit: true
        
    - name: Send success message to Telegram 
      if: ${{ success() }}
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          Success ${{ github.job }}
          ${{ github.actor }} created commit:
          Commit message: ${{ github.event.commits[0].message }}
          
          Repository: ${{ github.repository }}
