name: cicd-static-app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.1

    - name: Setup Node.js
      uses: actions/setup-node@v4.0.4
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run linters
      run: npm run lint
